{%- import "template/dockerfile.j2" as docker -%}
{%- import "template/environment.j2" as env -%}
{%- import "template/configs.j2" as configs -%}
{%- import "template/required.j2" as required -%}

{{ docker.fromOfficial(sourceImage, sourceTag) }}
{{ docker.label() }}
{{ env.general() }}
{{ docker.shell('["/bin/bash", "-c"]') }}
{{ required.install_main_pakage() }}
{{ required.install_tini("v0.19.0") }}
{{ required.add_user() }}
{{ configs.general() }}
{{ required.configure() }}
{{ required.install_rclone() }}
{{ required.clean_up() }}
{{ docker.expose(2222) }}
{{ docker.workdir("/tmp") }}
{{ docker.user("$UID") }}
{{ docker.cmd('["/bin/sh", "-c", "exit 0"]') }}

