{%- import "template/dockerfile.j2" as docker -%}
{%- import "template/environment.j2" as env -%}
{%- import "template/configs.j2" as configs -%}
{%- import "template/required.j2" as required -%}

{{ docker.fromOfficial(sourceImage, sourceTag) }}
{{ docker.arg("INTERPRETER") }}
{{ docker.arg("INTERPRETER_VERSION") }}
{{ docker.label() }}
{{ env.general() }}
{{ env.noninteractive() }}
{{ docker.shell('["/bin/bash", "-c"]') }}
{{ required.install_tini("v0.19.0") }}
{{ required.install_pip_package(packages) }}
{{ required.add_user() }}
{{ docker.workdir("/tmp") }}
{{ docker.user("$UID") }}
{{ docker.cmd('["/bin/sh", "-c", "exit 0"]') }}
