#!/usr/bin/env bash

origin_commit="$(git rev-parse --short HEAD)"
echo "origin_commit: ${origin_commit}"
files_to_commit="$(git diff --name-only ${origin_commit}^)"
echo "files_to_commit: ${files_to_commit}"

for image_path in $( cut -d'/' -f1,2 <<< "${files_to_commit}" | uniq ); do
  if [[ $image_path = images/* ]]; then
    image_full_path="$(git rev-parse --show-toplevel)"/"${image_path}"
    j2 -f json ${image_full_path}/dockerfile.j2 ${image_full_path}/metadata.json -o ${image_full_path}/Dockerfile
    git add ${image_full_path}/Dockerfile
    git commit -m "Update Dockerfile in ${image_full_path}"
  fi
done