{%- import "template/dockerfile.j2" as docker -%}
{%- import "template/environment.j2" as env -%}
{%- import "template/configs.j2" as configs -%}
{%- import "template/required.j2" as required -%}

{{ docker.fromOfficial(sourceImage, sourceTag) }}
{{ docker.arg("INTERPRETER") }}
{{ docker.arg("INTERPRETER_VERSION") }}
{{ docker.label() }}
{{ env.general() }}
{{ docker.shell('["/bin/bash", "-c"]') }}
{{ required.install_main_pakage() }}
{{ required.install_python() }}
{{ required.add_user() }}
{{ configs.general() }}
{{ required.configure() }}
{{ required.install_conda() }}
{{ required.install_pip() }}
{{ required.create_link() }}
{{ required.install_default_pip_package() }}
{{ required.install_pip_package(packages) }}
{{ required.install_rclone() }}
{{ required.clean_up() }}
{{ docker.expose(2222) }}
{{ docker.expose(8888) }}
{{ docker.workdir("/tmp") }}
# R packages
RUN conda install -c conda-forge --quiet --yes \
    'r-base=4.0.0' \
    'r-caret=6.*' \
    'r-crayon=1.3*' \
    'r-devtools=2.3*' \
    'r-forecast=8.12*' \
    'r-hexbin=1.28*' \
    'r-htmltools=0.4*' \
    'r-htmlwidgets=1.5*' \
    'r-irkernel=1.1*' \
    'r-nycflights13=1.0*' \
    'r-randomforest=4.6*' \
    'r-rcurl=1.98*' \
    'r-rmarkdown=2.2*' \
    'r-rodbc=1.3*' \
    'r-rsqlite=2.2*' \
    'r-shiny=1.4*' \
    'r-tidyverse=1.3*' \
    'unixodbc=2.3.*' \
    'r-tidymodels=0.1*' \
    && conda clean --all -f -y

# Install e1071 R package (dependency of the caret R package)
RUN conda install -c conda-forge --quiet --yes r-e1071

{{ docker.user("$UID") }}
{{ docker.cmd('["/bin/sh", "-c", "exit 0"]') }}
