{%- import "template/dockerfile.j2" as docker -%}
{%- import "template/environment.j2" as env -%}
{%- import "template/configs.j2" as configs -%}
{%- import "template/required.j2" as required -%}

{{ docker.fromOfficial(sourceImage, sourceTag) }}
{{ docker.arg("INTERPRETER") }}
{{ docker.arg("INTERPRETER_VERSION") }}
{{ docker.label() }}
{{ env.general() }}
{{ docker.shell('["/bin/bash", "-c"]') }}
{{ required.install_main_pakage() }}
{{ required.install_python() }}
{{ required.add_user() }}
{{ configs.general() }}
{{ required.configure() }}
{{ required.install_conda() }}
{{ required.install_pip() }}
{{ required.create_link() }}
{{ required.install_default_pip_package() }}
{{ required.install_pip_package(packages) }}
{{ required.install_rclone() }}
{{ required.clean_up() }}
{{ docker.expose(2222) }}
{{ docker.expose(8888) }}
{{ docker.workdir("/tmp") }}
# R packages
ENV DEBIAN_FRONTEND noninteractive

RUN add-apt-repository --enable-source --yes "ppa:marutter/rrutter4.0" \
    && add-apt-repository --enable-source --yes "ppa:c2d4u.team/c2d4u4.0+" \
    apt-get update \
        && apt-get install -y --no-install-recommends \
             littler \
 		     r-base \
 		     r-base-dev \
 		     r-recommended \
  	&& ln -s /usr/lib/R/site-library/littler/examples/install.r /usr/local/bin/install.r \
 	&& ln -s /usr/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
 	&& ln -s /usr/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
 	&& ln -s /usr/lib/R/site-library/littler/examples/testInstalled.r /usr/local/bin/testInstalled.r \
 	&& install.r docopt pillar IRkernel \
 	&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
    && apt-get clean \
 	&& rm -rf /var/lib/apt/lists/*

{{ docker.user("$UID") }}
{{ docker.cmd('["/bin/sh", "-c", "exit 0"]') }}
