{%- import "template/dockerfile.j2" as docker -%}
{%- import "template/environment.j2" as env -%}
{%- import "template/configs.j2" as configs -%}
{%- import "template/required.j2" as required -%}

{{ docker.fromOfficial(sourceImage, sourceTag) }}
{{ docker.arg("INTERPRETER") }}
{{ docker.arg("INTERPRETER_VERSION") }}
{{ docker.label() }}
{{ env.general() }}
{{ docker.shell('["/bin/bash", "-c"]') }}
{{ required.install_main_pakage() }}
{{ required.install_python() }}
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         lib${INTERPRETER}-dev \
         libopenblas-dev \
         pbzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

{{ required.add_user() }}
{{ configs.general() }}
{{ required.configure() }}
{{ required.install_conda() }}
{{ required.install_pip() }}
{{ required.create_link() }}
{{ required.install_default_pip_package() }}
{{ required.install_pip_package(packages) }}
{{ required.install_h2o4gpu }}
{{ required.install_rclone() }}
{{ required.clean_up() }}
{{ docker.expose(2222) }}
{{ docker.expose(8888) }}
{{ docker.workdir("/tmp") }}
{{ docker.user("$UID") }}
{{ docker.cmd('["/bin/sh", "-c", "exit 0"]') }}
